<footer>
	<div class="container">
		<div class="row footer">
			<div class="col-sm-4">
				<p><b>Dirección</b></p>
				<span>Montecaseros 2478 | Ciudad</span><br>
				<span>Mendoza | C.P. 5500</span><br>
			</div>
			<div class="col-sm-4">
				<p><b>E-Mails</b></p>
				<span><a href="mailto:administracion@analizar-lab.com.ar">administracion@analizar-lab.com.ar</a></span><br>
				<span><a href="mailto:mega@analizar-lab.com.ar">mega@analizar-lab.com.ar</a></span><br>
				<span><a href="mailto:gerencia@analizar-lab.com.ar">gerencia@analizar-lab.com.ar</a></span><br>
			</div>
			<div class="col-sm-4">
				<p><b>Tel / Fax</b></p>
				<a class="pull-right" href="http://qr.afip.gob.ar/?qr=WGen2MMMQCwrtVTeL9b6zw,," target="_F960AFIPInfo">
					<img src="http://www.afip.gob.ar/images/f960/DATAWEB.jpg" border="0" width="30">
				</a>
				<span><a href="tel:+5492614373241">+54 261 437 32 41</a></span><br>
				<span><a href="tel:+5492614373242">+54 261 437 32 42</a></span><br>
				<span><a href="tel:+5492614412362">+54 261 441 23 62</a></span><br>
			</div>
		</div>
	</div>
</footer>