<?php if ($this->messages) : ?>
    <?php foreach ($this->messages as $message) : ?>
        <div class="alert-floating alert alert-<?php echo $message['type'] ?> noRadius alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <?php echo $message['message'] ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<script type="text/javascript">
    function message(type,message,destino){
        if (type==""){
            $(destino).html('');
            return true;
        }
        var html='';
        html+=' <div class="alert alert-'+type+' noRadius alert-dismissable">';
        html+='<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>';
        html+=message;
        html+='</div>';
        if ($(destino)){
            $(destino).html(html);
        }
    }
</script>