<ol class="breadcrumb noRadius">
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
	<li class="breadcrumb-item active">Notas</li>
</ol>
<h2 class="gray">Notas</h2>
<hr class="condensed">
<?php foreach ($this->entities as $key => $entity): ?>
	<div class="row box-news hand transition" onclick="location.href='<?php echo $this->url(array('id'=>$entity["ne_id"]),'nota'); ?>'">
		<div class="col-sm-4 ">
			<div class="fill" style="border: #DDD solid 1px; height:200px; background-image: url(<?php echo $this->baseUrl()."/files/".$entity["ne_picture"]; ?>)">
			</div>
		</div>
		<div class="col-sm-8">
			<h3 class="title green"><?php echo ucfirst(strtolower($entity["ne_title"]));?></h3>
			<p class="text-muted"><span class="glyphicon glyphicon-calendar"></span> <?php echo date("d/m/Y",strtotime($entity["ne_date"]));?></p>
			<p><?php echo CutText(nl2br($entity["ne_description"]),25); ?></p>
		</div>
	</div>
	<hr>
<?php endforeach ?>