<div class="row">
    <div class="col-sm-8">
        <form method="get" id="form1" action="<?php echo $this->url(array('action'=>'search','method'=>'form1')); ?>" >
            <blockquote>
                <?php if ($this->method=='form1'): ?>
                    <button class="btn btn-xs btn-info pull-right" type="button" onclick="location.href='<?php echo $this->url(array('action'=>'rm')); ?>'">Quitar filtro</button>
                <?php endif ?>
                <p class="text-primary">Fecha / Bioquímico</p>
                <div class="row">
                    <div class="col-xs-6">
                        <input type="text" name="fecha" id="fecha" class="form-control calendar" readonly="readonly" value="<?php echo $this->fecha ?>">
                    </div>
                    <div class="col-xs-6">
                        <select class="form-control autocomplete" name="matricula" id="matricula" placeholder="Bioquímico">
                            <option value="">--Seleccione un Bioquímico --</option>
                            <?php foreach ($this->biochemicals as $key => $value): ?>
                                <option value="<?php echo $value['BMatricula'] ?>" <?php echo ($value['BMatricula']==$this->matricula)?'selected="selected"':''; ?>><?php echo $value['BMatricula'] ?> - <?php echo $value['BNombre'] ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </blockquote>
        </form>
    </div>
    <div class="col-sm-4">
        <blockquote>
            <?php if ($this->method=='form2'): ?>
                <button class="btn btn-xs btn-info pull-right" type="button" onclick="location.href='<?php echo $this->url(array('action'=>'rm')); ?>'">Quitar filtro</button>
            <?php endif ?>
            <p class="text-primary">Nro de Muestra</p>
            <input type="number" name="muestra" id="muestra" class="form-control" value="<?php echo $this->muestra ?>" onkeyup="is_enter(event);">
        </blockquote>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <tr>
            <th><a href='<?php echo $this->url(array('sort'=>'RMuestra','order'=>($this->parameters['order']=='ASC')?'DESC':'ASC')); ?>'>Nº Muestra</a></th>
            <th><a href='<?php echo $this->url(array('sort'=>'BMatricula','order'=>($this->parameters['order']=='ASC')?'DESC':'ASC')); ?>'>Matrícula</a></th>
            <th><a href='<?php echo $this->url(array('sort'=>'BNombre','order'=>($this->parameters['order']=='ASC')?'DESC':'ASC')); ?>'>Bioquímico</a></th>
            <th><a href='<?php echo $this->url(array('sort'=>'RFecha','order'=>($this->parameters['order']=='ASC')?'DESC':'ASC')); ?>'>Fecha</a></th>
            <th><a href='<?php echo $this->url(array('sort'=>'RCreated','order'=>($this->parameters['order']=='ASC')?'DESC':'ASC')); ?>'>Publicado</a></th>
            <th class="text-center"><a href='<?php echo $this->url(array('sort'=>'Aviso','order'=>($this->parameters['order']=='ASC')?'DESC':'ASC')); ?>'>Email enviado</a></th>
        </tr>
        <?php if (count($this->results) > 0):?>
            <?php foreach ($this->results as $keyRow => $result): ?>
                <tr onclick="openModalScript('iframe','<b>Nº Muestra: <?php echo $result["RMuestra"] ?></b>',null,'<?php echo $this->url(array('action'=>'load','popup'=>true,'RMuestra'=>$result["RMuestra"]));?>','70%','500px')">
                    <td><b><?php echo $result["RMuestra"] ?></b></td>
                    <td><?php echo $result["BMatricula"] ?></td>
                    <td><?php echo $result["BNombre"] ?></td>
                    <td><?php echo $result["RFecha"] ?></td>
                    <td><?php echo date("d/m/Y H:i",$result["RCreated"]) ?></td>
                    <td class="text-center"><?php echo ($result["Aviso"]==1)?'<b>SI</b>':'<b>NO</b>'; ?></td>
                </tr>
            <?php endforeach;?>
        <?php else: ?>
            <tr>
                <td colspan="6">
                    <div class="alert alert-info"><b>No se encontraron resultados</b> <?php echo ($this->search) ? '- Intente con otro criterio de busqueda' : ''; ?></div>
                </td>
            </tr>  
        <?php endif; ?>
    </table>
    <div class="text-center">
        <?php echo $this->paginationControl($this->results, 'Sliding', 'paginationControl.phtml'); ?>
    </div>
</div>
<script type="text/javascript">
    $(function (){
        $('#fecha').change(sendForm1);
        $(".autocomplete").combobox({ 
            select: function (event, ui) { 
                sendForm1();
            } 
        }); 
    });
    function rm(form){
        $('#fecha').val('');
        $('#matricula').val('');
        $('#muestra').val('');
        sendForm1();
    }
    function sendForm1(){
        $('#form1').submit();
    }
    function is_enter(e) {
        if (e.keyCode == 13 && $("#muestra").val().length > 3 ) {
            location.href='<?php echo $this->url(array('action'=>'search','method'=>'form2')); ?>?muestra='+$("#muestra").val()
        }
    }


</script>
<!-- <div id="charts"></div>
<script>
    $(function(){
        Highcharts.chart('charts', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Monthly Average Rainfall'
            },
            subtitle: {
                text: 'Source: WorldClimate.com'
            },
            xAxis: {
                categories: [
                'Ene',
                'Feb',
                'Mar',
                'Abr',
                'May',
                'Jun',
                'Jul',
                'Ago',
                'Sep',
                'Oct',
                'Nov',
                'Dec'
                ],
                crosshair: true
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Rainfall (mm)'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: 'Tokyo',
                data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

            }, {
                name: 'New York',
                data: [83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3]

            }, {
                name: 'London',
                data: [48.9, 38.8, 39.3, 41.4, 47.0, 48.3, 59.0, 59.6, 52.4, 65.2, 59.3, 51.2]

            }, {
                name: 'Berlin',
                data: [42.4, 33.2, 34.5, 39.7, 52.6, 75.5, 57.4, 60.4, 47.6, 39.1, 46.8, 51.1]

            }]
        });
    });
</script>
<script src="<?php echo $this->baseUrl() ?>/bower_components/highcharts/highcharts.js"></script>
<script src="<?php echo $this->baseUrl() ?>/bower_components/highcharts/modules/exporting.js"></script> -->