
<form id="form" method="post" novalidate enctype="multipart/form-data">
    <div class="row">
        <div class="form-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Formato de imagen JPG,PNG o GIF.
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label>Archivo</label>
                        <br/>
                        <input type="file" id="file" name="file" class="form-control">
                        <?php if ($this->parameters["resize"]): ?>
                            <div class="checkbox">
                                <?php
                                $resize = explode('|', $this->parameters["resize"]);
                                ?>
                                Tamaño recomendado: <?php echo $resize[0] ?>x<?php echo $resize[1] ?> px 
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="btn-group">
                        <button type="submit" name="submit" value="photo" class="btn btn-info" data-loading-text="Validando...">Subir</button>
                        <button type="button" class="btn btn-default" onclick='window.parent.closeModal();'>Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</form>