<ol class="breadcrumb noRadius">
  <li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
  <li class="breadcrumb-item active">Contáctenos</li>
</ol>
<div class="icon-lg">
	<div class="row">
		<div class="col-sm-6 col-md-3 text-center ">
			<span class="fa-stack fa-lg green transition">
				<i class="fa fa-circle fa-stack-2x"></i>
				<i class="fa fa-flask fa-stack-1x fa-inverse"></i>
			</span>
			<h3>Determinaciones</h3>
		</div>
		<div class="col-sm-6 col-md-3 text-center ">
			<span class="fa-stack fa-lg green  transition">
				<i class="fa fa-circle fa-stack-2x"></i>
				<i class="fa fa-newspaper-o fa-stack-1x fa-inverse"></i>
			</span>
			<h3>Notas</h3>
		</div>
		<div class="col-sm-6 col-md-3 text-center ">
			<span class="fa-stack fa-lg green transition">
				<i class="fa fa-circle fa-stack-2x"></i>
				<i class="fa fa-check fa-stack-1x fa-inverse"></i>
			</span>
			<h3>Calidad</h3>
		</div>
		<div class="col-sm-6 col-md-3 text-center ">
			<span class="fa-stack fa-lg green transition">
				<i class="fa fa-circle fa-stack-2x"></i>
				<i class="fa fa-sitemap fa-stack-1x fa-inverse"></i>
			</span>
			<h3>Organización</h3>
		</div>
	</div>
</div>