<!DOCTYPE html>
<html>
<head>
    <title>
        <?php echo $this->setting["se_title"]; ?>
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php
    echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/imgs/favicon.png'))
    ->prependStylesheet($this->baseUrl() . '/css/estilos.css')
    ->prependStylesheet($this->baseUrl() . '/css/estilos-xs.css')
    ->prependStylesheet($this->baseUrl() . '/css/estilos-sm.css')
    ->prependStylesheet($this->baseUrl() . '/css/estilos-md.css')
    ->prependStylesheet($this->baseUrl() . '/css/estilos-lg.css')
    ->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css')
    ->prependStylesheet($this->baseUrl() . '/css/jquery-ui.css')
    ;
    echo $this->headScript()    
    ->prependFile($this->baseUrl() . '/js/bootstrap.min.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/jquery-ui.min.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/jquery-1.9.1.js', 'text/javascript')
    ;
    ?>
</head>
<body>
    <?php echo $this->layout()->content; ?> 
</body>
</html>