<!DOCTYPE html>
<html>
<head>
    <title>
        <?php echo $this->setting["se_title"]; ?>
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php
    echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/images/favicon.ico'))
    ->prependStylesheet($this->baseUrl() . '/css/estilos.css')
    ->prependStylesheet($this->baseUrl() . '/css/estilos-lg.css')
    ->prependStylesheet($this->baseUrl() . '/css/estilos-md.css')
    ->prependStylesheet($this->baseUrl() . '/css/estilos-sm.css')
    ->prependStylesheet($this->baseUrl() . '/css/estilos-xs.css')    
    ->prependStylesheet($this->baseUrl() . '/css/estilos-xxs.css')
    ->prependStylesheet($this->baseUrl() . '/css/bootstrap-theme.min.css')
    ->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css')
    ->prependStylesheet($this->baseUrl() . '/font-awesome-4.5.0/css/font-awesome.min.css')
    ->prependStylesheet($this->baseUrl() . '/css/jquery-ui.css')
    ;
    echo $this->headScript()    
    ->prependFile($this->baseUrl() . '/js/bootstrap.min.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/jquery-ui.min.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/jquery-1.9.1.js', 'text/javascript')
    ;
    ?>
    <link href="<?php echo $this->baseUrl() ?>/css/bootstrap.min.css" media="print" rel="stylesheet" type="text/css" >
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet">
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-96113466-1', 'auto');
      ga('send', 'pageview');

  </script>
</head>
<body>
    <div class="hidden-print"><?php echo $this->render('_menu.phtml'); ?></div>
    <div class="text-center visible-print" style="margin-bottom: -70px;"><img src="<?php echo $this->baseUrl()."/imgs/meganalizar/meganalizar_logo.png";?>"></div>
    <div class="container" style="background: #FFF; padding-top: 100px; padding-bottom: 15px;">
        <?php echo $this->render('_messages.phtml'); ?>
        <?php echo $this->layout()->content;?>
    </div>
    <div class="bg-green hidden-print">
        <?php echo $this->render('_footer.phtml'); ?>
    </div>
    <?php echo $this->render('_modal.phtml'); ?>
    <script type="text/javascript">
        $(".calendar").datepicker({
            changeMonth: true,
            changeYear: true
        });
        $.datepicker.regional['es'] = {
            closeText: 'Cerrar',
            prevText: '&#x3c;Ant',
            nextText: 'Sig&#x3e;',
            currentText: 'Hoy',
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
            'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun',
            'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            dayNames: ['Domingo', 'Lunes', 'Martes', 'Mi&eacute;rcoles', 'Jueves', 'Viernes', 'S&aacute;bado'],
            dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mi&eacute;', 'Juv', 'Vie', 'S&aacute;b'],
            dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'S&aacute;'],
            weekHeader: 'Sm',
            dateFormat: 'dd/mm/yy',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: ''};
            $.datepicker.setDefaults($.datepicker.regional['es']);
        </script>
    </body>
    </html>