<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title><?php echo $this->setting["se_title"]; ?></title>
    <style type="text/css">
    body {
        -webkit-text-size-adjust: none;
        -ms-text-size-adjust: none;
    }
    html,
    body {
        margin: 0;
        padding: 0;
        border: 0;
        outline: 0;
    }
    table td {
        border-collapse: collapse;
        border-spacing: 0px;
        border: 0px none;
    }
    
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    p,
    i,
    b,
    a,
    ul,
    li,
    blockquote,
    hr,
    img,
    div,
    span,
    strong {
        margin:0;
        padding:0;
    }
    a,
    a:link {
        text-decoration: underline;
    }
    img {
        border: 0 none;
        outline: none;
        line-height: 100%;
        outline: none;
        text-decoration: none;
        vertical-align: bottom;
    }
    a{
        color: #009688;
    }
    a img {
        border: 0 none;
    }
    footer a {
        text-decoration: none;
        color: #FFF !important;
    }

</style>
<style>
@import url('https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,boldi,500');
</style>
</head>
<body bgcolor="#F2F2F2" style="color: #616161;padding: 0px; margin: 0px;">
    <table width="760" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
        <tr>
            <td bgcolor="#FFFFFF" width="100%" height="93" valign="middle" cellspacing="20" style="background-color: #FFF;">
                <a href="http://www.meganalizar.com.ar/" style="text-decoration: none;">
                    <img border="0" src="http://www.meganalizar.com.ar/public/imgs/meganalizar/meganalizar_logo.png" alt="Logo Meganalizar" width="231" style="margin-left: 20px;" />
                </a>
            </td>
        </tr>
        <tr>
            <td style="margin-top: 0; padding-top: 0px; padding-bottom: 15px; font-family:'Montserrat', sans-serif; font-weight: 300; font-size: 14px;line-height: 20px;">
                <hr style="border:none; border-bottom: #CCC solid 1px;">
                <div style="padding: 30px 15px;">
                    <?php echo $this->layout()->content; ?> 
                </div>
            </td>
        </tr>
        <tr>
            <td  width="100%"  valign="middle"  style="background-color: #009688; color:#FFF ;padding:15px; font-family:'Montserrat', sans-serif; font-weight: 300; font-size: 12px;">
                <footer>
                    <table width="100%">
                        <tr>
                            <td>
                                <p style="font-size: 14px;"><b>Dirección</b></p>
                                <span style="color: #FFF !important;">Montecaseros 2478 | Ciudad</span><br>
                                <span>Mendoza | C.P. 5500</span><br>
                            </td>
                            <td>
                                <p><b>E-Mails</b></p>
                                <span><a href="mailto:administracion@analizar-lab.com.ar"  style="color: #FFF !important;">administracion@analizar-lab.com.ar</a></span><br>
                                <span><a href="mailto:mega@analizar-lab.com.ar" style="color: #FFF !important;">mega@analizar-lab.com.ar</a></span><br>
                                <span><a href="mailto:gerencia@analizar-lab.com.ar" style="color: #FFF !important;">gerencia@analizar-lab.com.ar</a></span><br>
                            </td>
                            <td>
                                <p><b>Tel / Fax</b></p>
                                <span><a href="tel:+5492614373241" style="color: #FFF !important;">+54 261 437 32 41</a></span><br>
                                <span><a href="tel:+5492614373242" style="color: #FFF !important;">+54 261 437 32 42</a></span><br>
                                <span><a href="tel:+5492614412362" style="color: #FFF !important;">+54 261 441 23 62</a></span><br>
                            </td>
                        </tr>
                    </table>
                </footer>
            </td>
        </tr>
    </table>
</body>
</html>