<?php echo $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title><?php echo $this->setting["se_title"]; ?></title>
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/images/favicon.ico'))
    ->prependStylesheet($this->baseUrl() . '/font-awesome-4.5.0/css/font-awesome.min.css')
    ->prependStylesheet($this->baseUrl() . '/css/admin.css')
    ->prependStylesheet($this->baseUrl() . '/css/plugins/metisMenu/metisMenu.min.css')
    ->prependStylesheet($this->baseUrl() . '/css/bootstrap-theme.css')
    ->prependStylesheet($this->baseUrl() . '/css/bootstrap.css')
    ->prependStylesheet($this->baseUrl() . '/css/jquery-ui.css')
    ->prependStylesheet($this->baseUrl() . '/css/imgareaselect-default.css')
    ->prependStylesheet($this->baseUrl() . '/css/bootstrap-rta-1.0.1.min.css');
    echo $this->headScript()
    ->prependFile($this->baseUrl() . '/extras/ckeditor_4.6.2_full/ckeditor/ckeditor.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/jquery.nicescroll.min.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/Common.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/plugins/metisMenu/metisMenu.min.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/jquery.form.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/bootstrap.validate.en.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/bootstrap.validate.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/popover.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->baseUrl() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->baseUrl() . '/js/bootstrap.min.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/jquery-ui.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/tether.min.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/jquery.imgareaselect.pack.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/jquery-1.11.3.min.js', 'text/javascript')
    ->prependFile($this->baseUrl() . '/js/holder.js', 'text/javascript')
    ;
    ?>
</head>
<body>
    <?php echo $this->render('messages.phtml', array('messages' => $this->messages)); ?>
    <?php echo $this->layout()->content; ?>
</body>
</html>
