<ol class="breadcrumb noRadius">
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'organizacion'); ?>">Organización</a></li>
	<li class="breadcrumb-item active">Autoridades</li>
</ol>
<div class="row myAccount">
	<?php echo $this->render('organization/partial/menu.phtml'); ?>
	<div class="col-sm-9">
		<h2>Autoridades</h2>
		<hr class="condensed">
		<p><b>DIRECTORIO ACTUAL DE ANALIZAR S.A.</b></p>
		<div class="row">
			<div class="col-sm-4">				
				<p>
					<b>Presidente:</b> Dr. Carlos Paravano<br/>
					<b>Vicepresidente:</b> Dr. Alfredo Matile<br/>
				</p>
			</div>
			<div class="col-sm-4">
				<p><b>Directores Titulares</b><br/>
					Dr. Renato D`Inca <br/>
					Dr. Ricardo Molina <br/>
					Dr.  Gustavo Yapur<br/>
				</p>
			</div>
			<div class="col-sm-4">
				<p><b>Directores Suplentes</b><br/>
					Dra. Cristina Brizuela de Pecere<br/>
					Dr. María José Barcaglioni <br/>
					Dra. María Clara Pott Godoy<br/>
				</p>
				<p><b>Responsable de la Calidad</b><br/>
					Dra. Cristina Brizuela de Pecere<br/>

				</p>
			</div>
		</div>
		<hr class="condensed">
		<table style="width: 100%; text-align: center;" border ="0">
			<tr>
				<td width="33%"></td>
				<td width="33%">
					<p><b>Gerente General</b><br/>
						Cayetano Accordino<br/>
						<img src="<?php echo $this->baseUrl() ?>/imgs/cayetano.jpg" style="border:#CCC solid 1px;"/>
					</p>
				</td>
				<td width="33%"></td>
			</tr>
			<tr><td colspan="3">&nbsp;</td></tr>
			<tr>
				<td width="33%"></td>
				<td width="33%">
					<p><b>Director Técnico y de Producción</b><br/>
						Dr. Eneas Español<br/>
						<img src="<?php echo $this->baseUrl() ?>/imgs/eneas_espanol.jpg" style="border:#CCC solid 1px;"/>
					</p>
				</td>
				<td width="33%">
					<p><b>Área de Administración</b><br/>
						Lic. Gabriela Authiévre<br/>
						<img src="<?php echo $this->baseUrl() ?>/imgs/gabriela.jpg" style="border:#CCC solid 1px;"/>
					</p>
				</td>
			</tr>
			<tr><td colspan="3">&nbsp;</td></tr>
			<tr>
				<td width="33%">
					<p><b>Sector de Inmunología<br/>
					y Análisis Manuales</b><br/>
					Dra. Carla Keller<br/>
					<img src="<?php echo $this->baseUrl() ?>/imgs/carla_keller.jpg" style="border:#CCC solid 1px;"/>
				</p>
				</td>
				<td width="33%">
					<!--<p><b>Responsable de Sector <br/>Hematología</b><br/>
						Dra. Cecilia Gómez<br/>
						<img src="<?php echo $this->baseUrl() ?>/imgs/cecilia_gomez.jpg" style="border:#CCC solid 1px; width: 122px; height: 122px;"/>
					</p>-->
				</td>
				<td width="33%">
					<p><b>Jefe de Técnicas<br/></b><br/>
						Técnica Silvina Baldo<br/>
						<img src="<?php echo $this->baseUrl() ?>/imgs/silvina_baldo.jpg" style="border:#CCC solid 1px;"/>
					</p>
				</td>
			</tr>
			<tr><td colspan="3">&nbsp;</td></tr>
			<tr>
				<td width="33%">
					<p>
					<b>
					&nbsp;
					<br/></b>
						<br/>Dra. Cecilia Gómez<br/>
						<img src="<?php echo $this->baseUrl() ?>/imgs/cecilia_gomez.jpg" style="border:#CCC solid 1px;"/>
					</p>
				</td>
				<td width="33%">

				</td>
				<td width="33%">
					<p><b>Auxiliares Técnicas Administrativas<br/></b>
						<br/>Técnica Pamela Villalba<br/>
						<img src="<?php echo $this->baseUrl() ?>/imgs/pamela_villalba.jpg" style="border:#CCC solid 1px;"/>
					</p>
				</td>
			</tr>
			<tr><td colspan="3">&nbsp;</td></tr>
			<tr>
				<td width="33%">
					<p><b>
					Sector Alta Complejidad
					<br/> y Química Clínica</b>
						<br/>Dra. Lucía Herrera<br/>
						<img src="<?php echo $this->baseUrl() ?>/imgs/lucia_herrera.jpg" style="border:#CCC solid 1px;"/>
					</p>
				</td>
				<td width="33%">

				</td>
				<td width="33%">
					<p>&nbsp;<br/><br/>Técnica Jésica Gonzalez<br/>
						<img src="<?php echo $this->baseUrl() ?>/imgs/gonzalez.jpg" style="border:#CCC solid 1px;"/>
					</p>
				</td>
			</tr>
			<tr>
				<td width="33%">
					<p><b>Sector de Hematología</b>
						<br/>Dr. Gonzalo Nardella<br/>
						<img src="<?php echo $this->baseUrl() ?>/imgs/gonzalo_nardella.png" style="border:#CCC solid 1px;"/>
					</p>
				</td>
				<td width="33%">

				</td>
				<td width="33%">
				<p><br/>Técnica Vanesa Villalobos<br/>
					<img src="<?php echo $this->baseUrl() ?>/imgs/vanesa_villalobos.jpg" style="border:#CCC solid 1px;"/>
				</p>
				</td>
			</tr>

		<tr>
			<td width="33%">
				
			</td>
			<td width="33%">

			</td>
			<td width="33%">
				<p><br/>Técnica Marcela López<br/>
					<img src="<?php echo $this->baseUrl() ?>/imgs/lopez.jpg" style="border:#CCC solid 1px;"/>
				</p>
			</td>
		</tr>
		
	</table>
	<!-- <hr class="condensed">
	<img src="<?php echo $this->baseUrl() . '/imgs/autoridades.jpg' ?>" alt="organigrama" width="100%">  -->
</div>
</div>