<ol class="breadcrumb noRadius">
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'organizacion'); ?>">Organización</a></li>
	<li class="breadcrumb-item active">Historia</li>
</ol>
<div class="row myAccount">
	<?php echo $this->render('organization/partial/menu.phtml'); ?>
	<div class="col-sm-9">
		<h2>Historia</h2>
		<hr class="condensed">
		<p>CONSTITUCION DE ANALIZAR S.A. Analizar S.A. quedo constituida en Mendoza, el 10 de agosto de 1994, Inscripta en el Registro Público de Comercio el 19.10.1994 Escritura 31 Legajo 2985 a fs. 1 y 31.</p>
		<div class="row">
			<div class="col-sm-6">
				<div class="fill" style="height:230px; background-image: url(<?php echo $this->baseUrl() . '/imgs/historia1.jpg'?>)"></div>
			</div>
			<div class="col-sm-6">
				<div class="fill" style="height:230px; background-image: url(<?php echo $this->baseUrl() . '/imgs/historia2.jpg'?>)"></div>
			</div>
		</div>
		<br>        
		<h4 class="green">PRIMER DIRECTORIO</h4>
		<p>
			Presidente: Dra. Perla Raquel Chaves <br/>
			Directores Titulares: DRES. ORLANDO MONETTI, ALFREDO MATILE, RAUL DE VECCHI, MIGUEL NELSON PALMADA. <br>
			Síndico Titular. Contador Juan Carlos Sónego, Síndico <br>
			Suplente. Dr. Jorge González Parejas.
		</p>
		<h4 class="green">HISTORIA</h4>
		<p>En el año 1996, con el país entrando en la ya conocida crisis económica, la Comisión Directiva de la Asociación Bioquímica de Mendoza, encabezada por la Dra. Perla Chaves y el Dr. Orlando Monetti, (Presidente y Vicepresidente en ese momento ) preocupada por el futuro de la profesión, comprobaron que a nuestra Red de prestadores bioquímicos les resultaba muy difícil acceder en sus laboratorios a tecnología de última generación, con controles de calidad normatizados.</p>
		<p>A esto se sumó la oferta de megalaboratorios de Buenos Aires, cuyo principal interés es comercial, tratando de captar muestras en nuestro medio. Por tales motivos se concretó la creación de un megalaboratorio institucional que diera respuesta a estas necesidades y prestara un servicio a todos los laboratorios que aún contando con profesionales capacitados, no podían acceder a los avances tecnológicos con precios competitivos en el mercado.</p>
		<p>Hoy, años después, contamos con un equipo de trabajo formado por profesionales y técnicos capacitados que se esfuerzan diariamente para dar una respuesta rápida y eficiente a los colegas de gran parte de nuestra provincia, con el soporte tecnológico de aparatología de primer nivel y con el apoyo de una gran empresa internacional, cuyos directivos nos brindan constantemente la colaboración y asesoramiento necesario para seguir mejorando.</p>
		<p>Además se está implementando un sistema de Gestión de Calidad, que nos permite estar en condiciones de acceder a la acreditación por la norma ISO 15189 Mercosur.</p>
		<p>Brindamos a los colegas, desde lo institucional y profesional, las herramientas imprescindibles de calidad, a lo que se suma la rapidez en la entrega de resultados, así como el beneficio de pago diferido.</p>
		<p>En síntesis, Meganalizar es un emprendimiento que pertenece a todos los bioquímicos que lo adoptaron como propio y fundamental para la actividad bioquímica</p>
	</div>
</div>