<ol class="breadcrumb noRadius">
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'organizacion'); ?>">Organización</a></li>
	<li class="breadcrumb-item active">Introducción</li>
</ol>
<div class="row myAccount">
	<?php echo $this->render('organization/partial/menu.phtml'); ?>
	<div class="col-sm-9">
		<h2>Introducción</h2>
		<hr class="condensed">
		<div class="fill" style="height:230px; background-image: url(<?php echo $this->baseUrl() . '/img/micro1.jpg'?>)"></div>
		<br>
		<p>
			Inaugurado el 28 de Noviembre de 1996. Empezó a funcionar en la ciudad de 
			Mendoza en diciembre de 1996, en calle Montecaseros 2478. Cuenta con la más moderna 
			tecnología de punta y lo coloca a la vanguardia de los servicios bioquímicos del país. 
			Este es un emprendimiento organizado por la casi totalidad de los bioquímicos del Gran 
			Mendoza a través de Analizar S.A. y que cuenta con el auspicio de la Asociación Bioquímica
			de Mendoza, por ser concebido como un servicio mutuo profesional que se traduce en la 
			excelencia de las prestaciones que se brindan, es decir de indudable beneficio social. 
		</p>
	</div>
</div>