<ol class="breadcrumb noRadius">
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'organizacion'); ?>">Organización</a></li>
	<li class="breadcrumb-item active">Visión & Misión</li>
</ol>
<div class="row myAccount">
	<?php echo $this->render('organization/partial/menu.phtml'); ?>
	<div class="col-sm-9">
		<h2>Visión & Misión</h2>
		<hr class="condensed">
		<div class="fill" style="height:230px; background-image: url(<?php echo $this->baseUrl() . '/img/labo1.jpg'?>)"></div>
		<br>
		<h4 class="green">NUESTRA MISIÓN</h4>
		<p>- Proteger las fuentes de trabajo de los laboratorios pequeños y medianos asociados al permitirles competir con tecnología, calidad y bajos costos.</p>
		<p>- Asegurar el más óptimo nivel de calidad y la homogeneidad de los resultados de los análisis por utilizar el mejor respaldo tecnológico verificado mediante adecuados y oportunos procedimientos de calificación de los instrumentos y la participación en programas de control de calidad.</p>
		<p>- Optimizar la prestación bioquímica permitiendo tener la mejor respuesta en el menor tiempo posible.</p>
		<p>- Ofrecer a los laboratorios derivantes la más amplia oferta de servicios analíticos para tratar de cubrir lo más completamente posible la demanda médica regional.</p>
		<br>
		<h4 class="green">NUESTRA VISIÓN</h4>
        <p>  - Estar acreditado según los lineamientos de la Norma NM ISO 15189 - Ser un laboratorio reconocido por la eficiencia y eficacia de sus servicios.</p>
        <p>- Contar con la infraestructura adecuada al crecimiento y desarrollo del laboratorio. - Disponer de suficiente personal especializado en cada área de trabajo y comprometido en un equipo de trabajo consustanciado con la calidad.</p>
        <p>- Brindar la mayor cobertura de servicios analíticos de la región. Expandir el área de influencia a provincias vecinas.</p>
        <p>- Ser un activo colaborador de las autoridades sanitarias en programas de fomento de hábitos saludables, prevención y educación y en situaciones de emergencias, epidemias, pandemias, catástrofes, desastres naturales y deliberados, o situaciones de urgencia nacional.</p> 
	</div>
</div>