<div class="col-sm-3">
	<div class="list-group noRadius hidden-xs" style="font-size: 13px;">
		<a href="<?php echo $this->url(array(),'calidad'); ?>" class="list-group-item <?php echo ($this->parameters['action']=='index')?'active':''; ?>">
			Introducción
		</a>
        <a href="<?php echo $this->url(array(),'certificacion'); ?>" class="list-group-item <?php echo ($this->parameters['action']=='certificate')?'active':''; ?>">
			Certificación
		</a>
		<a href="<?php echo $this->url(array(),'politicas'); ?>" class="list-group-item <?php echo ($this->parameters['action']=='policies')?'active':''; ?>">
			Políticas de calidad
		</a>
		<a href="<?php echo $this->url(array(),'objetivos'); ?>" class="list-group-item <?php echo ($this->parameters['action']=='target')?'active':''; ?>">
			Objetivos generales
		</a>
	</div>
	<div class="btn-group visible-xs" style="width: 100%;">
		<ul class="dropdown-menu">
			<?php if ($this->parameters['action']!='index'):?>
				<li>
					<a href="<?php echo $this->url(array(),'calidad'); ?>">
						Introducción
					</a>
				</li>
			<?php else: ?>
				<?php $current='Introducción' ?>
			<?php endif; ?>
            <?php if ($this->parameters['action']!='certificate'):?>
                <li>
                    <a href="<?php echo $this->url(array(),'certificacion'); ?>">
                        Certificación
                    </a>
                </li>
            <?php else: ?>
                <?php $current='Introducción' ?>
            <?php endif; ?>
			<?php if ($this->parameters['action']!='policies'):?>
				<li>
					<a href="<?php echo $this->url(array(),'politicas'); ?>">
						Políticas de calidad
					</a>
				</li>
			<?php else: ?>
				<?php $current='Políticas de calidad' ?>
			<?php endif; ?>
			<?php if ($this->parameters['action']!='target'):?>
				<li>
					<a href="<?php echo $this->url(array(),'objetivos'); ?>">
						Objetivos generales
					</a>
				</li>
			<?php else: ?>
				<?php $current='Objetivos generales' ?>
			<?php endif; ?>
		</ul>
		<button type="button"  class="btn btn-block btn-primary dropdown-toggle noRadius" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<?php echo $current ?> <i class="fa fa-bars" aria-hidden="true"></i>
		</button>
	</div>
	<div style="height: 50px;"></div>
</div>