<ol class="breadcrumb noRadius">
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
	<li class="breadcrumb-item active">Datos Útiles</li>
</ol>
<h2 class="gray">Datos útiles</h2>
<hr class="condensed">
<?php if ($this->entities): ?>
	<div class="table-responsive">
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th>Nombre</th>
					<th class="text-right"></th>
				</tr> 
			</thead>
			<tbody>
				<?php foreach ($this->entities as $key => $value):?>
					<tr class="hand" onclick="location.href='<?php echo $this->url(array('id'=>$value['he_id']),'datoutil');?>'">
						<td><?php echo $value['he_name'] ?></td>
						<td class="text-right">
							<a><span class="glyphicon glyphicon-eye-open"></span> <span class="hidden-xs">Ver más</span></a>
						</td>
					</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
<?php else: ?>
	<p>No se encontraron resultados</p>
<?php endif;?>