<ol class="breadcrumb noRadius">
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
	<li class="breadcrumb-item active">Contacto</li>
</ol>
<div class="row">
	<div class="col-sm-6">
		<h2 class="gray">Nos interesa su consulta</h2>
		<hr class="condensed">
		<form method="POST" onsubmit="$('#btnSend').attr('disabled',true);" action="<?php echo $this->url(array('controller'=>'contact','action'=>'send'),'default',true) ?>">
			<div class="form-container">
				<div class="form-group">
					<label>Nombre completo</label>
					<input type="text" name="nombre" placeholder="Nombre completo" class="form-control noRadius" value="">
				</div>
				<div class="form-group">
					<label>Teléfono</label>
					<input type="text" name="telefono" placeholder="Teléfono" class="form-control noRadius" value="">
				</div>
				<div class="form-group">
					<label>Email</label>
					<input type="text" name="email" placeholder="Email" class="form-control noRadius" value="">
				</div>
				<div class="form-group">
					<label>Consulta</label>
					<textarea placeholder="Consulta" class="form-control noRadius" name="consulta" rows="5"></textarea>
				</div>
				<hr class="condensed">
				<div class="btn-group pull-right">
					<button class="btn btn-primary noRadius" id="btnSend" type="submit">Enviar consulta</button>
				</div>
			</div>
		</form>
	</div>
	<div class="col-sm-6">
		<h2 class="gray">Contáctenos</h2>
		<hr class="condensed">
		<br>
		<p><span class="glyphicon glyphicon-map-marker green"></span> Montecaseros 2478 | Ciudad Mendoza | C.P. 5500</p>
		<p><span class="glyphicon glyphicon-phone-alt green"></span> <a href="tel:+5492614373241">+54 261 437 32 41</a> | <a href="tel:+5492614373242">+54 261 437 32 42</a></p>
		<p><span class="glyphicon glyphicon-envelope green"></span> <a href="mailto:administracion@analizar-lab.com.ar">administracion@analizar-lab.com.ar</a> | <a href="mailto:mega@analizar-lab.com.ar">mega@analizar-lab.com.ar</a></p>
		<div id="map" style="width: 100%;height: 315px;"></div>
	</div>
</div>
<script>
      function initMap() {
        var uluru = {lat: -32.874425, lng: -68.830680};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCNj3-soT2HznW8fzcFx8G1IqYh6XiA5qE&callback=initMap">
    </script>