<div class="col-xs-12">
    <div class="panel panel-default">
        <div class="panel-heading">Equipos de procesamiento</div>
        <div class="panel-body">
            <?php foreach ($this->equipments as $key => $eq): ?>
                <div class="form-group col-md-3 col-sm-6">
                    <div class="checkbox">
                        <label >
                        <input type="checkbox" <?php echo ($this->formDisabled == true) ? " disabled " : ""; ?> <?php echo (in_array($key,$this->equipments_selected))?"checked='checked'":""?> name="equipments[<?php echo $key ?>]" value="1"> <b><?php echo $eq ?></b>
                        </label>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>