<div class="row">
    <div class="form-group col-xs-6">
        <label>Precio $</label>
        <input class="form-control" value="<?php echo $this->parameters["price"] ?>" id="price" />
    </div>
</div>
<div class="form-group">
    <label>Valores de referencia</label>
    <textarea class="form-control" id="reference"><?php echo $this->parameters["reference"] ?></textarea>
</div>
<div class="btn-group">
    <button type="button" class="btn btn-info" onclick='sendInformation();'>Aceptar</button>
    <button type="button" class="btn btn-default" onclick='closeModal();'>Cancelar</button>
</div>
<script>
    function sendInformation(){
        var price=parseFloat($("#price").val());
        var reference=$("#reference").val();
        var la_id='<?php echo $this->parameters["la_id"] ?>';
        $("#"+la_id+"_price").html("$ "+price);
        $("#"+la_id+"_reference").html(reference);
        $("#input_"+la_id+"_price").val(price);
        $("#input_"+la_id+"_reference").val(reference);
        closeModal();
    }
</script>