<ol class="breadcrumb noRadius">
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'calidad'); ?>">Calidad</a></li>
	<li class="breadcrumb-item active">Introducción</li>
</ol>
<div class="row myAccount">
	<?php echo $this->render('quality/partial/menu.phtml'); ?>
	<div class="col-sm-9">
		<h2>Introducción</h2>
		<hr class="condensed">
		<div class="fill" style="height:230px; background-image: url(<?php echo $this->baseUrl() . '/img/labo2.jpg'?>)"></div>
		<br>
		<p>La Política de Calidad de Meganalizar es lograr la satisfacción 
			de los laboratorios derivantes y, a través de ellos, de la 
			comunidad médica en su zona de influencia por medio de la 
		excelencia de sus servicios. </p>
		<p>Este objetivo se desarrolla mediante el trabajo en equipo 
			de todos los integrantes de Analizar S.A., buscando la motivación, 
			la plena integración y la satisfacción del personal, con el 
		apoyo de la formación continua. </p>
		<p>Meganalizar apuesta a la mejora continua, la única vía para 
			asegurar la mejor calidad analítica en todos sus sentidos 
			y mantener nuestra posición de liderazgo en el sector de los 
		efectores de salud de la Provincia de Mendoza. </p>
		<p>Es vital para Meganalizar la mejora en las relaciones con 
			los bioquímicos derivantes y nuestros proveedores, ya que 
		el camino hacia el progreso lo debemos recorrer conjuntamente. </p>
		<p>En estas premisas están implicados todos los miembros de 
			Analizar S.A., los cuales, mediante un trato común cordial 
			y respetuoso, lucharán por la excelencia en todo aquello que 
		realicen. </p>
		<p>Estos objetivos, política y acciones están reflejados en 
			este Manual de Calidad de Meganalizar, en el Manual de Procedimientos 
			y en aquellos documentos necesarios para el cumplimiento de 
			las diferentes tareas, así como en toda la documentación complementaria 
		que forma parte del Sistema de Gestión de la Calidad</p>
	</div>
</div>