<ol class="breadcrumb noRadius">
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'calidad'); ?>">Calidad</a></li>
	<li class="breadcrumb-item active">Políticas de Calidad</li>
</ol>
<div class="row myAccount">
	<?php echo $this->render('quality/partial/menu.phtml'); ?>
	<div class="col-sm-9">
		<h2>Políticas de Calidad</h2>
		<hr class="condensed">
		<div class="fill" style="height:230px; background-image: url(<?php echo $this->baseUrl() . '/img/labo3.jpg'?>)"></div>
		<br>
		<p>Asegurar la calidad de los análisis procesados mediante el uso de la mejor tecnología disponible, la realización de adecuados y oportunos controles de calidad internos y externos y una eficiente gestión de la calidad.</p>
       <p> Propender a la renovación y ampliación tecnológica del laboratorio para asegurar la actualización y optimización de los servicios prestados.</p>
        <p>Permitir la formación continua y el perfeccionamiento del personal del laboratorio.</p>
        <p>Comprometer e involucrar a todo el personal de Meganalizar con el Sistema de Calidad en cuanto a su permanente conocimiento e implementación de las políticas y procedimientos correspondientes a fin de asegurar la mejora continua de los servicios.</p>
        <p>Realizar tareas formativas e informativas con los profesionales de los laboratorios que utilizan los servicios de Meganalizar con el objeto de mejorar su respaldo científico frente a la demanda médica y asegurar las mejores condiciones preanalíticas en las muestras de modo de garantizar la calidad de los resultados obtenidos.</p>
        <p>Buscar la mejora de la rentabilidad a los laboratorios derivantes a través del uso de métodos de probada calidad al más bajo costo posible.</p>
	</div>
</div>