<ol class="breadcrumb noRadius">
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'inicio'); ?>">Inicio</a></li>
	<li class="breadcrumb-item"><a href="<?php echo $this->url(array(),'calidad'); ?>">Calidad</a></li>
	<li class="breadcrumb-item active">Objetivos generales</li>
</ol>
<div class="row myAccount">
	<?php echo $this->render('quality/partial/menu.phtml'); ?>
	<div class="col-sm-9">
		<h2>Objetivos generales</h2>
		<hr class="condensed">
		<div class="fill" style="height:230px; background-image: url(<?php echo $this->baseUrl() . '/img/labo4.jpg'?>)"></div>
		<br>
		<p>Para cumplir con las Políticas enunciadas que permiten a este emprendimiento acercarse a lograr su Misión, Meganalizar tiene fijados objetivos generales que cubren todos los aspectos de la Política de Calidad, el compromiso con la mejora continua y la satisfacción de los requisitos de nuestros servicios.</p>
		<p>Utilizar la mejor tecnología disponible para optimizar la prestación bioquímica, buscando el más bajo costo posible manteniendo la mejor calidad analítica, con el objeto de aumentar la rentabilidad económica de los laboratorios derivantes y su prestigio en la comunidad.</p>
		<p>Mejorar la información y formación de los bioquímicos de los laboratorios derivantes sobre los requisitos necesarios para satisfacer las condiciones que las pruebas bioquímicas requieren y sobre la gestión y el aseguramiento de la calidad de acuerdo a las disposiciones legales y reglamentarias vigentes.</p>
		<p>Brindar a los bioquímicos derivantes y a la comunidad médica en general, información actualizada que permita la mejor interpretación de la información bioquímica obtenida con los métodos utilizados.</p>
		<p>Optimizar la calificación del personal del laboratorio mediante su formación continua y el perfeccionamiento de su capacitación en las áreas que les competen.</p> 
		<p>Estos objetivos de calidad generales se complementan con objetivos de calidad particulares que se establecen después de realizar la revisión del sistema de gestión de la calidad, ya que el resultado de la misma es de vital importancia para definirlos.</p>
	</div>
</div>