<div class="col-xs-12" style="padding-top: 15px;">
    <div class="panel panel-info">
        <div class="panel-heading text-center">
            Newsletter a enviar: <?php echo $this->result["nl_title"] ?>
        </div>
        <div class="panel-body condensed">
            <div class="progress">
                <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:<?php echo $this->percent ?>%">
                    <span style="display: block; color: black; position: absolute; width: 90%;">Enviando <?php echo $this->percent ?>%</span>
                </div>
            </div>
            <div style="height: 300px; overflow: auto; border: #EFEFEF solid 1px; padding: 5px; margin: 5px;">
                <?php foreach ($this->biochemicals as $key => $biochemical): ?>
                    <?php if ($biochemical["nr_receiver"]):?>
                        <div class="form-group col-sm-6 col-md-4">
                            <?php if ($biochemical["nr_status"]==0): ?>
                                <?php if ($biochemical["nr_id"]==$this->next['nr_id']): ?>
                                    <b><?php echo $biochemical["nr_receiver"] ?> - Enviando ...</b>
                                <?php else: ?>
                                    <?php echo $biochemical["nr_receiver"] ?>
                                <?php endif ?>
                            <?php else: ?>
                                <b><i><?php echo $biochemical["nr_receiver"] ?> - Enviando OK</i></b>
                            <?php endif ?>
                        </div>
                    <?php endif ?>
                <?php endforeach ?>
            </div>
        </div>
        <div class="panel-footer text-center">
            <b>No cierre esta ventana, ya que interrumpiria el proceso de envío.</b>
        </div>
    </div>
</div> 
<script>
    var pagina='<?php echo $this->url(array('action'=>'send','id' => $this->result['nl_id'], 'next_id' => $this->next['nr_id'])); ?>';
    var tiempo=<?php echo $this->interval ?>;
    function redir() { 
        location.href=pagina;
    }
    setTimeout ("redir()", tiempo); 
</script>
<?php if ($this->close): ?>
<script>
    window.opener.location.reload(); window.close();
</script>
<?php endif; ?>